### PR TITLE
Define exit_on_failure? to suppress thor's warning

### LINKED ISSUE #342: Thor Deprecation warning
I got the error below when using this command

````
itamae --test local /home/nedim/neidiom/test/lib/itamae/nginx.rb
````
````
ERROR: "itamae help" was called with arguments ["--test", "local", "/home/nedim/neidiom/test/lib/itamae/nginx.rb"]
Usage: "itamae help [COMMAND]"
Deprecation warning: Thor exit with status 0 on errors. To keep this behavior, you must define `exit_on_failure?` in `Itamae::CLI`
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
````

### PR DESCRIPTION
**Pull request by unasuke**
fix #342

see it → https://github.com/rails/thor/pull/651

### CODE REVIEW

File: bin/itamae [hunk 1]
```diff
@@ -2,4 +2,3 @@
 
 require 'itamae/cli'
 Itamae::CLI.start
-
```
Comment (unasuke) [inline bin/itamae:5]: Cosmetic change 💄

File: lib/itamae/cli.rb [hunk 2]
```diff
@@ -36,6 +36,10 @@ def self.options
       end
     end
 
+    def self.exit_on_failure?
+      true
```
Comment (sue445) [inline lib/itamae/cli.rb:40]: I also agree with this behavior

**Review by sue445 — APPROVED** [review]
LGTM!
